#image: Visual Studio 2019
#
#install:
#  - ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
#  - ps: ./dotnet-install.ps1 -JsonFile global.json
#
#init:
#- git config --global core.autocrlf true
#
#environment:
#  DOTNET_VERSION: "7.0.100"
#
#build_script:
#- ps: dotnet pack -c Release -o artifacts
#
#artifacts:
#- path: artifacts\*.nupkg
#
#deploy:
#- provider: NuGet
#  server: https://www.myget.org/F/kharisovdf/api/v2
#  on:
#    branch: master
#    appveyor_repo_tag: false
#  api_key:
#    secure: auKf1d+9gbvV044GemD2GQzky1c5VwoAlDLSlAuMCwlHIYX7jsgPpk8rCmPnSLE0
#  skip_symbols: true
#
#- provider: NuGet
#  server: https://www.nuget.org/api/v2/package
#  on:
#    branch: master
#    appveyor_repo_tag: true
#  api_key:
#    secure: n2/xjxIcp8AMe5kJow4oMXmb5FaUKzmRIkBLXY/xVR/EvqEd7vD1r7iwPxfhcIE0
#  skip_symbols: true